baseURL: "https://wenrong-nexus.com/"
defaultContentLanguage: zh-hant
locale: zh-Hant # en-us
title: Wenrong Nexus
paginate: 5
theme: hugo-theme-stack

enableRobotsTXT: true
hasCJKLanguage: true

buildDrafts: false
buildFuture: false
buildExpired: false

services:
  googleAnalytics:
    id: G-GRV3BQC1BQ
  disqus:
    shortname: wenrongdev

minify:
  disableXML: true

taxonomies:
  tag: "tags"
  series: "series"

permalinks:
  posts: "/posts/:slug/"

params:
  mainSections: ["posts"]
  rssFullContent: true
  favicon: "/favicon.ico"

  footer:
    since: 2019
    customText: "Wenrong Nexus"

  sidebar:
    avatar: "/android-chrome-512x512.png"
    emoji: "🎮"
    subtitle: "我是 Wenrong 也是一位 Unity 工程師，開發常常會碰到跨平台觸坑問題，因此想寫個 Blog 紀錄填坑歷程。"

  article:
    headingAnchor: true
    toc: true
    readingTime: true

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  comments:
    enabled: true
    provider: disqus

menu:
  main:
    - identifier: home
      name: 首頁
      url: /
      weight: 1
      params:
        icon: home
    - identifier: search
      name: 搜尋
      url: /search/
      weight: 2
      params:
        icon: search
    - identifier: archives
      name: 歸檔
      url: /archives/
      weight: 3
      params:
        icon: archives
    - identifier: tags
      name: 標籤
      url: /tags/
      weight: 4
      params:
        icon: tag
    - identifier: about
      name: 關於我
      url: /profile/about/
      weight: 5
      params:
        icon: user

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/Wenrong274
      params:
        icon: brand-github
        newTab: true
    - identifier: email
      name: Email
      url: mailto:me@wenrong-nexus.com
      params:
        icon: user
        newTab: true
    - identifier: rss
      name: RSS
      url: /index.xml
      params:
        icon: rss
        newTab: true
